name: Shared Matrix

on: workflow_dispatch

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      color-list: ${{ steps.generate-colors.outputs.color-json }}

    steps:
      - name: Define Colors
        id: generate-colors
        run: |
          echo 'color-json=["red", "green", "blue"]' >> "$GITHUB_OUTPUT"

  produce-artifacts:
    runs-on: ubuntu-latest
    needs: define-matrix

    strategy:
      matrix:
        color: ${{ fromJSON(needs.define-matrix.outputs.color-list) }}

    steps:
      - name: Define Color
        env:
          color: ${{ matrix.color }}
        run: |
          echo "$color" > color

      - name: Produce Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.color }}
          path: color

      - name: Debug environment
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Runner temp: $RUNNER_TEMP"
          echo "Runner tool cache: $RUNNER_TOOL_CACHE"

      - name: Show tree
        run: |
          cd ..
          cd ..
          echo "PWD:"
          pwd
          echo "------"
          echo "ls -a: "
          ls -a
          echo "-----"
          sudo apt-get install -y tree   # ubuntu runners have apt
          echo "Tree"
          tree -L 3
          echo "-----"

  consume-artifacts:
    runs-on: ubuntu-latest

    needs:
      - define-matrix
      - produce-artifacts

    strategy:
      matrix:
        color: ${{ fromJSON(needs.define-matrix.outputs.color-list) }}

    steps:
      - name: Retrieve Artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ matrix.color }}

      - name: Report Color
        run: |
          cat color
